### PR TITLE
normal flow tested by verified NP

### PR DESCRIPTION
**Pull request by fsgithub2024**
It is tested by validation utility. @sandeepshahi  Please review and elaborate your suggestion if anything missed.

### CODE REVIEW

**Comment by fsgithub2024** [comment]
> It is tested by validation utility. @sandeepshahi Please review and elaborate your suggestion if anything missed.

I'm have tried recon on the same data, that's why there is changes only on a timestamp.

**Comment by sandeepshahi** [comment]
@fsgithub2024, mocking of requests is not allowed; Use either the mock server utility or test with a counterparty NP with RSF services enabled.

**Comment by sandeepshahi** [comment]
@fsgithub2024, please share a demo video of RSF. Since, the buyer app is reference buyer app in the receiver_recon, would request you to show the demo video testing with the same;

**Comment by fsgithub2024** [comment]
@sandeepshahi Video for the normal and correction flow? Do we need to share on the same github repo or any other process?

**Comment by sandeepshahi** [comment]
@fsgithub2024, yes. Please share the link of google drive and upload it along with the logs.

**Comment by fsgithub2024** [comment]
Okay @sandeepshahi

**Pull request closed without merging**
