### PR TITLE
SellerSetu Logs - Retail Seller App

### PR DESCRIPTION
**Pull request by Ikshan-Tango**
Adding SellerSetu (seller-app) logs for RETAIL and IGM.
Retail logs consist of domain ONDC:RET16 with Flow 1, Flow 2 and Flow 3.

### CODE REVIEW

**Comment by Ikshan-Tango** [comment]
@bluecypher We had used log validation utility and it was giving us false errors. We had raised this issue firstly on the community call as well as mailed to the ONDC tech team and we were advised to continue to log validation while ignoring these false errors. Attaching a screenshot for your reference as well. 

image

**Comment by Ikshan-Tango** [comment]
@sandeepshahi, awaiting your response.

**Comment by sandeepshahi** [comment]
I can check several errors in the catalog itself, which are flagged by the utility if utilized. For eg: the value of inventory availability should be either 0 or 99 where 0 means out of stock and 99 means available.  

Also, the item tags should have a code: "attribute" instead of "Home and Kitchen"

@Ikshan-Tango

**Comment by sandeepshahi** [comment]
Request to fix the issues and resubmit the PR.

**Pull request closed without merging**
