### PR TITLE
Added RET11 Seller logs

### PR DESCRIPTION
**Pull request by RaviV-Protean**

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
@RaviV-Protean, please use the log validation utility to perform a sanity before submitting the logs. Also, flow 3 is incomplete, please provide the complete flow with remaining items in the cart.

**Comment by RaviV-Protean** [comment]
Hi @sandeepshahi, Before submission we have already ran log validation utility. If you want we can share responses as well along with curl requests.

**Comment by sandeepshahi** [comment]
@RaviV-Protean, Yes, please provide the curl for all the flows.

**Comment by RaviV-Protean** [comment]
Alright @sandeepshahi, we are submitting logs along with reports. But Meanwhile can we please consider flow 3 out-of-stock without entire order, as entire order is being sent in flow 2, 5, 6. **We will submit flow 3 with order delivery in sometime.**

**Pull request closed without merging**
