### PR TITLE
Updated IGM Flow 2 as per the feedback

### PR DESCRIPTION
**Pull request by udyamwell1**
@sandeepshahi Please merge this pull request

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
@udyamwell1, please submit the logs after testing with a counterparty NP; Manipulating the previously submitted logs is not allowed.

@udyamwell1

**Comment by udyamwell1** [comment]
@sandeepshahi okay sure, we will submit retail logs after testing. 
And re-submitting IGM logs separately. Thank-you!

**Review by udyamwell1 — COMMENTED** [review]
We will resubmit the updated flows of retail

**Comment by udyamwell1** [comment]
We are working on Retail flows. 
Can you please merge the IGM Flow 2? 
@sandeepshahi

**Review by sandeepshahi — APPROVED** [review]

**Pull request merged**
