### PR TITLE
Ekart Logistics seller provider v1.2 logs

### PR DESCRIPTION
**Pull request by tushar-jaiswal17**

### CODE REVIEW

**Comment by tushar-jaiswal17** [comment]
@sandeepshahi Please verify

**Review by abhinavv245 — COMMENTED** [review]
Please confirm if you have used the [log validation tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to self test the submitted logs?

**Comment by tushar-jaiswal17** [comment]
@abhinavv245 No, I was not aware about this step.
I will check the tool and update once done.

**Comment by abhinavv245** [comment]
Sure, Please update the PR once you have rectified the issues identified by the utility. Let me know if you have any questions.

**Comment by tushar-jaiswal17** [comment]
@abhinavv245 Verified the logs using utility and rectified the issues.
Raised the PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/2186

**Pull request closed without merging**
