### PR TITLE
fashion pulse RET12 Seller Logs

### PR DESCRIPTION
**Pull request by kanwaljeet-shekhawat**

### CODE REVIEW

**Comment by kanwaljeet-shekhawat** [comment]
@sandeepshahi   Kindly merge and review the logs

**Review by sandeepshahi — APPROVED** [review]

**Comment by sandeepshahi** [comment]
@kanwaljeet-shekhawat, CA will be assigned for the validation process. Please provide the SPOC contact details for the compliance procedure.

**Comment by kanwaljeet-shekhawat** [comment]
@sandeepshahi  hi ,
Please find my email :- kanwaljeet.shekhawat@eshiksa.in  

If you need ant other detail please let me know

**Comment by kanwaljeet-shekhawat** [comment]
@sandeepshahi  hi , i haven't got any further information regarding validation process, can you please let me know what's the tat for the same

**Pull request merged**
