### PR TITLE
DIGILEDGE SELLER v1.2 logs submitted

### PR DESCRIPTION
**Pull request by shabirahamed**

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Why aren't flow 2 and 3 tested again? 

@shabirahamed

**Comment by shabirahamed** [comment]
Flow 2 and flow 3 logs were verified and cleared

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Please fix all the issues as raised in the issue board; Also, test entire scenarios and avoid changing the attributes/values and submit all the logs.

@shabirahamed

**Comment by sandeepshahi** [comment]
@shabirahamed, Pls address all the issues and resubmit the PR.

**Pull request closed without merging**
