### PR TITLE
Updated Retails logs based on the feedback

### PR DESCRIPTION
**Pull request by udyamwell1**
We have updated the logs based on the feedback. Please review it.

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
All the scenarios in Flow 6 must be part of the same order transaction similar to the other flows.

@udyamwell1

**Comment by sandeepshahi** [comment]
@udyamwell1, please also submit the utility report while resubmitting the PR and in case any issues are identified, pls get them fixed.

**Comment by udyamwell1** [comment]
> All the scenarios in Flow 6 must be part of the same order transaction similar to the other flows.
> 
> @udyamwell1

Okay sure, we will work on flow 6. thanks for the review.

**Comment by udyamwell1** [comment]
> @udyamwell1, please also submit the utility report while resubmitting the PR and in case any issues are identified, pls get them fixed.

Every time, we submitted logs after checking with the utility. We will work on flow 6 and submit it separately with utility report. thankyou

**Pull request closed without merging**
