### PR TITLE
GlobalLinker Logs v1.2.0

### PR DESCRIPTION
**Pull request by Tjsvaradhan**

### CODE REVIEW

**Review by sandeepshahi — APPROVED** [review]

**Comment by sandeepshahi** [comment]
@Tjsvaradhan, please remove the older logs and submit only the latest logs to avoid any confusion.

**Comment by Tjsvaradhan** [comment]
Sandeep,



We have created a PR for deleting the current directory to do fresh upload
of logs as suggested – please approve & merge.



https://github.com/ONDC-Official/v1.2.0-logs/pull/1193



Thanks

**Comment by Tjsvaradhan** [comment]
Sandeep,



We have submitted our logs again – please refer to the PR:
https://github.com/ONDC-Official/v1.2.0-logs/pull/1194



Please review and confirm.



We have included all final logs submitted so far for Grocery, Fashion, BPC,
Electronics Appliances and Health & Wellness



*Note:*

Please approve the delete PR (
https://github.com/ONDC-Official/v1.2.0-logs/pull/1193)

as given in the email below first.



Thanks

**Comment by Tjsvaradhan** [comment]
Hi Sandeep / Sahil,
Any update on the Log Review for the PR given below? We submitted last
Tuesday / 26-Mar-2024.
Thanks

**Pull request merged**
