### PR TITLE
Zyro retail (RET10)

### PR DESCRIPTION
**Pull request by Dipu6669**
Zyro retail (RET10)process Logs Added. Please Review

### CODE REVIEW

**Comment by Dipu6669** [comment]
@sandeepshahi Please Review

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
@Dipu6669, could you please confirm if the log validation utility reports are clear for all the flows?

**Comment by Dipu6669** [comment]
@sandeepshahi, Yes the flows were validated using utility except Flow6. there were some issues regarding liquidation flow.
but Today I am getting a lot of valition issues from the utility as there was an update to the utility.

**Comment by sandeepshahi** [comment]
@Dipu6669, can you please fix those errors and resubmit the PR. In case of any issues/concern with the utility, you may raise an issue on log utility's issue board.

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
@Dipu6669, why are 2 separate folders created for the same set of logs?

**Pull request closed without merging**
