### PR TITLE
SellerSetu BA:RET16 IGM & SA:RET13,18 Flow 1 fix

### LINKED ISSUE #2199: Sellersetu (SA : RET10,12,13,14,15,18) - Compliance check
---
### on_search
- `@ondc/org/time_to_ship` & `@ondc/org/return_window` cannot be `P0D`.
---
### on_search_inc
- There is no difference at any level except timestamp.
—
### on-search
- GTIN code should be valid. Eg: 194252656740 is invalid. please validate it on https://www.gs1india.org/gtin-validation/

### on_search_inc
- timestamp should be updated at the time of change in item.
—--
### on-search
- GTIN code should be valid. Eg: 8801643708540 is invalid. please validate it on https://www.gs1india.org/gtin-validation/

### on_search_inc
- How is `items.time.timestamp` future dated when compared with `context.timestamp`?
---
### on_search && on_search_inc
- `@ondc/org/time_to_ship` cannot be `P0D`.
- circle.gps can’t be ‘,’.
---

@sellersetu-hub

### PR DESCRIPTION
**Pull request by Chaitanya-Keyal**
#2199 for SA:RET13,18

### CODE REVIEW

**Comment by sellersetu-hub** [comment]
Have renamed BPP-Retail to BPP

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
@Chaitanya-Keyal, BAP IGM logs seem invalid; The bap id and uri are not of the seller setu app.


Also, logs of domains other than 13 and 18 are also modified. Please confirm if the tech compliance checks need to be performed for them.

**Comment by sellersetu-hub** [comment]
> Also, logs of domains other than 13 and 18 are also modified. Please confirm if the tech compliance checks need to be performed for them

**Comment by sellersetu-hub** [comment]
> BAP IGM logs seem invalid; The bap id and uri are not of the seller setu app.

This is BAP if and uri are correct, BAP is subscribed using different domain.
@sandeepshahi

**Comment by sellersetu-hub** [comment]
Also @sandeepshahi we submited BAP logs from the same bap id and uri (preprod-ondc.letsboho.in)

**Review by sandeepshahi — APPROVED** [review]

**Comment by sellersetu-hub** [comment]
Also @sandeepshahi  can we get review on BAP logs both Retail and IGM

**Pull request merged**
