### PR TITLE
Tipplr SA - Added Retail(RET11) Logs as per compliance

### PR DESCRIPTION
**Pull request by punithrj26**
Hi there,

Have added retails logs as per compliance.
Have used log validation utlity. Have uploaded the request flow.
Please accept my pr.

Thanks

### CODE REVIEW

**Review by sandeepshahi — APPROVED** [review]

**Comment by sandeepshahi** [comment]
Please rectify the logs as per the feedback here: https://github.com/ONDC-Official/v1.2.0-logs/issues/650#issuecomment-2002682560

@punithrj26

**Comment by punithrj26** [comment]
Hi @sandeepshahi 

I have went through the comments mentioned in issue #650 .
I had used log validation utility, had got response as verified successfully.

Please check with the lasted merged pr (https://github.com/ONDC-Official/v1.2.0-logs/tree/master/Tipplr/seller-app-corrected-Mar-15(F%26B-RET11)/Group%20A) . 
Screenshot 2024-03-15 at 5 11 03 PM


Thank you.

**Comment by sandeepshahi** [comment]
@punithrj26, please remove all the previously submitted logs and submit only the latest logs. The NP folder seems to be cluttered with a lot of unnecessary folders.

**Comment by punithrj26** [comment]
@sandeepshahi 
Ok will remove unnecessary folders in next log submission.
Thanks.

**Pull request merged**
