### PR TITLE
PR for Agrikheti - RET11 flow

### PR DESCRIPTION
**Pull request by vikash-agrikheti**
Here, we have used the test case scenario and followed the existing flow of other NPs that have already been submitted by other NPs. Kindly let me know if anything is not in the proper format or if anything is missing. Please also let me know what the issue is, as I had emailed you earlier, but I did not receive any reply.

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Invalid PR;

For IGM: 2 flows must be submitted for self-logistics and 3 for on-network logistics
For RSF: All the 5 flows must be submitted
For Retail RET 11: Flow 3 and Flow 6 are missing; Also, do submit log validation utility report for all the flows as requested earlier too.

@vikash-agrikheti

**Comment by vikash-agrikheti** [comment]
Hi team,
Can you please clarify what is meant by submitting the log validation utility report for all the flows, as requested earlier?
Thanks & regards,
Vikash Kumar Singh
6396793362

________________________________

**Comment by vikash-agrikheti** [comment]
Hi Sandeep,
Can you please clarify what is meant by submitting the log validation utility report for all the flows, as requested earlier?
Thanks & regards,
Vikash Kumar Singh
6396793362

________________________________

**Comment by vikash-agrikheti** [comment]
Hi Sandeep,

As of now, we are using on-network logistics only. However, according to your suggestion:

  *   IGM: 2 flows must be submitted for self-logistics
  *   3 flows for on-network logistics.

Could you please clarify whether the self-logistics flow is mandatory or optional?
Looking forward to your response.
Best regards,
Vikash Kumar Singh
6396793362

________________________________

**Comment by vikash-agrikheti** [comment]
Hi Sandeep,

As discussed with Amit, since we are creating a buyer app, there is no need to develop the IGM self-logistics flow (2 flows).

Please let me know if you need any further clarification.

Best regards,
Vikash

**Pull request closed without merging**
