### PR TITLE
Resolve issues reported on dehaat seller and dehaat buyer app logs

### PR DESCRIPTION
**Pull request by vashistavivek**
https://github.com/ONDC-Official/v1.2.0-logs/issues/613#issue-2094673255
https://github.com/ONDC-Official/v1.2.0-logs/issues/570#issuecomment-1921974316

### CODE REVIEW

**Review by bluecypher — CHANGES_REQUESTED** [review]
Are there any differences in the logs submitted for both the buyer and seller apps in 2 different folders?

@vashistavivek

**Comment by vashistavivek** [comment]
@bluecypher No, we have used our own buyer and seller app to generate logs so they are same.

**Comment by bluecypher** [comment]
@vashistavivek, I would request to submit only one folder, will provide feedback for both the entity together.

**Comment by vashistavivek** [comment]
@bluecypher Done

**Comment by vashistavivek** [comment]
@bluecypher new PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/786

**Pull request closed without merging**
