### PR TITLE
Qwqer updated rsf logs

### PR DESCRIPTION
**Pull request by iamsajith**
Please review this pull request (re-submitted logs as per the [compliance](https://github.com/ONDC-Official/v1.2.0-logs/issues/1680)) at your earliest convenience.

@BLR-0118 @sandeepshahi @abhinavv245 @RupalSingla @JyotiSharma0711

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Manipulation of logs is not allowed. Please submit logs after testing with a counterparty NP.

@iamsajith

**Comment by iamsajith** [comment]
The order book in the /receiver_recon API of the deployed mock server (provided by ONDC) is always the same. We triggered the /push_receiver_recon again and received /receiver_recon from the mock server, and the callback (/on_receiver_recon) was triggered from our end. We submitted the payload according to the counterparty's request. We did not manipulate any data, and this issue is not on our end.

@sandeepshahi

**Comment by sandeepshahi** [comment]
@iamsajith, the txn id did not change in the logs and seems to be the same as used earlier

**Comment by iamsajith** [comment]
**Previous submission transaction IDs in the context are**

flow 1 => b9e0f922-4d7d-42d7-89e3-56647538d5d4
flow 2 => d86f3641-cb2e-4c8d-8a52-63295c1d8746

**This submission transaction IDs in the context are**

flow 1 => b6339d7a-b28b-4ab9-9f66-f4d21d57b8d9
flow 2 => b86ea46f-0ae8-4cdd-b546-216da838fac8


_The transaction IDs within the order are taken from the /receiver_recon API. Changing those IDs would be considered manipulation._

@sandeepshahi

**Comment by sandeepshahi** [comment]
@iamsajith, thanks for the explanation. The GitHub change logs got me confused.

**Pull request merged**
