### PR TITLE
Added tipplr seller app logs v1.2

### PR DESCRIPTION
**Pull request by punithrj26**
We are registered as a seller app. This contains logs for tipplr v1.2.0.

### CODE REVIEW

**Review by bluecypher — APPROVED** [review]
Flow 6 must be submitted for verification. Please use the log validation utility before submitting the logs.

https://github.com/ONDC-Official/log-validation-utility

@punithrj26

**Review by bluecypher — CHANGES_REQUESTED** [review]
Please check the feedback above and resubmit the logs

**Comment by bluecypher** [comment]
Please resubmit the logs as per the feedback above.

**Comment by punithrj26** [comment]
Ok sure, We are working on it,
Thank you, @bluecypher

**Pull request closed without merging**
