### PR TITLE
Resubmit Cosmos Retail logs RET10 22 Aug Flow1

### PR DESCRIPTION
**Pull request by vijendrakiko**

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
@vijendrakiko, please share the link of screenshots.

**Comment by vijendrakiko** [comment]
Hi @Sandeep Please check these screenshot links

https://kikonewapi.s3.ap-south-1.amazonaws.com/uploads/user_images/roGFXbia9G.png
https://kikonewapi.s3.ap-south-1.amazonaws.com/uploads/user_images/EYOKMOqYp.png
https://kikonewapi.s3.ap-south-1.amazonaws.com/uploads/user_images/cGjqDE35p.png

**Comment by sandeepshahi** [comment]
@vijendrakiko, please share the link of video demo on the issue board for all the scenarios

**Comment by vijendrakiko** [comment]
Okay sure I will do this

**Comment by Gururaj-KikoLive** [comment]
@sandeepshahi If there are any more changes or clarification required from our side please share it in one so we can submit all together.

**Review by sandeepshahi — APPROVED** [review]

**Pull request merged**
