### PR TITLE
Unistack igm

### PR DESCRIPTION
**Pull request by RaiManish3**
### Logs validation
The utility submission request and the response are present within the respective flow.

There was one issue reported by the tool. It was attributed to the ref-buyerapp.
From our end, no validation issues are reported.

### CODE REVIEW

**Comment by RaiManish3** [comment]
Hi @sandeepshahi ,
pls review this. Flow 2 was added in this PR.

**Review by sandeepshahi — APPROVED** [review]

**Comment by amitsinha07** [comment]
@RaiManish3 

# Unistack

## Flow 1

### issue

- **Issue 1**: Time of creation (`created_at`) and time of updation for `/issue` API should be the same.
- **Issue 2**: Context timestamp should be greater than or equal to `updated_at` in issue.
- **Issue 3**: `updated_at` is not matching with `message/issue/issue_actions/complainant_actions/[0]/updated_at`.

### issue_close

- **Issue**: `created_at` and `updated_at` should be the same.

### on_issue_status

- **Issue**: `updated_at` is not matching with `message/issue/issue_actions/respondent_actions/[1]/updated_at`.

## Flow 2

### issue

- **Issue 1**: Time of creation (`created_at`) and time of updation for `/issue` API should be the same.
- **Issue 2**: Context timestamp should be greater than or equal to `updated_at` in issue.

### issue_close

- **Issue**: `created_at` and `updated_at` should be the same.

### on_issue_status

- **Issue**: `updated_at` is not matching with `message/issue/issue_actions/respondent_actions/[1]/updated_at`.

**Comment by RaiManish3** [comment]
Hi @amitsinha07 

I had few doubts:
1. issue is created by the ref-buyer app. The error is generated at their end.
2. issue_close : it is also done at the buyer app side. should the created_at / updated be same for that?

**Comment by RaiManish3** [comment]
@amitsinha07

I have taken care of "on_issue_status" error reported in the above comments in PR 1641.
Please review.

**Pull request merged**
