### PR TITLE
Tipplr SA-Updated retail(ret11) logs as per compliance

### PR DESCRIPTION
**Pull request by punithrj26**
Hi there,
I have added the needs logs as per required.
Please merge my PR.
Thank you.

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Part cancellation is missing. Please submit this scenario as part of the same order in flow 6. 

@punithrj26

**Comment by punithrj26** [comment]
@sandeepshahi 
We have worked on flow 1 to 4.
Once first four flows are approved we will work on flow 5 and flow 6 parallelly.
Please merge and check flow 1 to flow 4.
Thank you.

**Comment by sandeepshahi** [comment]
@punithrj26, have you fixed the issues in Flow 5 and 6?

**Comment by punithrj26** [comment]
@sandeepshahi 
Yes we have added in the logs.
Please verify it.

**Review by sandeepshahi — APPROVED** [review]

**Pull request merged**
