### PR TITLE
Retail core workflow logs for Lekhha

### PR DESCRIPTION
**Pull request by ShaGup**
Retail core workflow logs for Lekhha

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Retail Core:
- Logs must be submitted after testing with a verified counterparty NP in preprod (testing with your own app should be avoided)
- After addressing all identified issues, provide the final report from the [log validation utility](https://github.com/ONDC-Official/log-validation-utility) for each flow.
- Review and resolve all the applicable items in the list of [manual validations](https://docs.google.com/document/d/1ROAGXqj5cJkgsNWvg_xiufglhqEQDJFBgQSPcFZMZd4/edit?tab=t.0) on your system before submitting logs for technical review.

IGM: 
- All the flows must be submitted for verification.

RSF:
- Logs must be submitted for verification

@ShaGup

**Comment by ShaGup** [comment]
Hi Sandeep, thanks for the mail.

Can you pls advise appropriate Buyer NP in Preprod to work with for testing
and creating logs?

Regards,
Shailesh.

**Comment by ShaGup** [comment]
Hi Pinky, Sandeep,

I started to use test with pramaan <https://ondc.org/pramaan/>, but I see
the following issues:
1. The catalog is not displaying multiple providers
2. Triggering select is NACKed with error 40004 because the select is
triggered with incorrect payment type: payment.type cannot be "PREPAID".
The 1.2.0 document says, valid eums for this field are: ON-ORDER,
ON-FULFILLMENT, POST-FULFILLMENT
Attached is the log file.

So unable to progress further with testing.

Regards,
Shailesh.

**Comment by ShaGup** [comment]
Attached is the log file.

Regards,
Shailesh.

**Comment by ShaGup** [comment]
Hi Sandeep,

Further to my previous email, we continued with the log validation utility
for the 6 flows.
Attached is the report from this utility.

While we are fixing the issues marked as 'Issue with self', we think many
of the validations are incorrect - all such errored validations are marked
as 'Issue with ONDC' (in the column C).
The reason for the same is mentioned in column D.

Please let me know a suitable time to discuss these.
Although the list appears long, the issues are actually repetitive.

Kind regards,
Shailesh.

**Pull request closed without merging**
