### PR TITLE
Craver RSF Flow

### PR DESCRIPTION
**Pull request by rudra-cruv**

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Invalid Submission; Logs must be submitted as per the test case scenarios (with /receiver_recon and /on_receiver_recon)

@rudra-cruv

**Comment by rudra-cruv** [comment]
We are a Buyer App on the RET11 domain. As per documentation, we can only call "collector_recon", "recon_status" and receive "on_collector_recon", "on_recon_status" from the RSP, "receiver_recon" and "on_receiver_recon" are to be implemented by the Seller App. How can we provide "receiver_recon" and "on_receiver_recon"?

@sandeepshahi

**Comment by sanidhyaagrawal** [comment]
@sandeepshahi bumping this.

tldr; as a **Buyer** App, we have correctly submitted /collector_recon and /on_collector_recon.

**Comment by sandeepshahi** [comment]
For RSF, the collector has to call /receiver_recon with the reconciliation related details and receiver has to acknowledge using /on_receiver_recon

@sanidhyaagrawal

**Comment by sanidhyaagrawal** [comment]
Hey @sandeepshahi, we are using Protean as our RSP. We only call `collector_recon` on Protean's endpoint and we only receive `on_collector_recon` from them.

`receiver_recon` and `on_receiver_recon` are called by Protean internally and we have nothing to do with it.

Please refer to the flow diagram between the collector and RSP below.

RSF

RSF

**Comment by sandeepshahi** [comment]
@sanidhyaagrawal, If you are using RSP services, there is no need to submit the logs. Please do mention it on the ONDC portal for final clearance

**Pull request closed without merging**
