### PR TITLE
Flow 1 and Flow 2 RETAIL ONDC:RET16 (Home and Kitchen) Logs

### PR DESCRIPTION
**Pull request by Ikshan-Tango**
This PR consists of Flow 1 and Flow for Home and kitchen domain of retail of SellerSetu.

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Please submit logs for all the flows as per the test case scenarios defined here: https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795

@Ikshan-Tango

**Comment by Ikshan-Tango** [comment]
@sandeepshahi only the incremental_request in Flow 1 is missing that's because we aren't receiving any incremental search requests from the Ref Buyer App. However we made a test call to our server by mocking a call and we're sharing the same payload. 
Apart from that we've adhered to the test case scenarios.

**Comment by sandeepshahi** [comment]
@Ikshan-Tango, no need to mock the request. The buyer app send incremental refresh at 1.30 am. Please make sure the city is registered as "*"

Apart from that you have to submit all the flows 1 to 6.

**Comment by Ikshan-Tango** [comment]
All righty will look into that incremental refresh request. 
Is it necessary to register city as "*" for all requests sent by us as a SNP?
Is it necessary to submit all flows together as other NP's are too submitting them partially one by one?

**Comment by sandeepshahi** [comment]
Yes, context/city should be * in incremental refresh
Yes, all the flows must be submitted at once; This is applicable for all the NPs.

**Comment by Ikshan-Tango** [comment]
Noted

**Pull request closed without merging**
