### PR TITLE
Api.lokal.in retail logs 19/04/2024

### PR DESCRIPTION
**Pull request by Srinath91**

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Please remove the files/folders uploaded on the root directory instead of the NP folder.

@Srinath91

**Comment by Srinath91** [comment]
@sandeepshahi Created new PR with correction : https://github.com/ONDC-Official/v1.2.0-logs/pull/1446

**Comment by sandeepshahi** [comment]
@Srinath91, please check again, the issue is still not resolved

**Comment by Srinath91** [comment]
@sandeepshahi Updated in PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/1457 .Please check

**Pull request closed without merging**
