### PR TITLE
feat: Added logs for aurikatech along with log validation reports.

### PR DESCRIPTION
**Pull request by vanshraghav**
Seller app API logs for aurikatech.com

The log validation utility reports are provided in the below JSON BLOB links

For Core APIs

Flow 1 - [Response](https://jsonblob.com/1245360840294391808)

Flow 2 - [Response](https://jsonblob.com/1245361311872573440)

Flow 3 - [Response](https://jsonblob.com/1245361460875223040)

Flow 4 - [Response](https://jsonblob.com/1245361989420441600)

Flow 5 - [Response](https://jsonblob.com/1245362104524726272)

Flow 6 - [Response](https://jsonblob.com/1245362233126281216)

For IGM flows

Flow 1 - [Response](https://jsonblob.com/1246024202443415552)

Flow 2 - [Response](https://jsonblob.com/1246024473760358400)

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Please remove the other folder and only keep the one with the NP name. 

@vanshraghav

**Comment by vanshraghav** [comment]
Hi @sandeepshahi ,
[Here](https://github.com/ONDC-Official/v1.2.0-logs/pull/1759/commits/cd07f02ab314c7b9b7c12068f61a0342decc765d) is the latest commit with the correct directory structure.

**Comment by sandeepshahi** [comment]
Invalid PR; Please check the files changed section.

@vanshraghav, please remove the other folder by the name SELLER-APP

**Comment by vanshraghav** [comment]
Hi @sandeepshahi ,

Added a new PR here https://github.com/ONDC-Official/v1.2.0-logs/pull/1766

**Pull request closed without merging**
