### PR TITLE
OrderPe Retail logs

### PR DESCRIPTION
**Pull request by Dipu6669**

### CODE REVIEW

**Comment by Dipu6669** [comment]
@sandeepshahi Please review and merge

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
@Dipu6669, please self test your logs with [log validation utility](https://github.com/ONDC-Official/log-validation-utility) and resubmit the logs after rectifying all the issues along with the utility report

**Comment by Dipu6669** [comment]
Hi @***@***.******@***.***>

These log validation utility report would be submitted with logs or separately over the email.

Thanks,
Dipu
________________________________

**Comment by Dipu6669** [comment]
@sandeepshahi : Do I need to submit the log validation utility report with the logs?

**Pull request closed without merging**
