### PR TITLE
Shopalyst - RET11 logs

### PR DESCRIPTION
**Pull request by Deepanjalitr**

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
@Deepanjalitr, is the log validation utility report clear for all the flows?

**Comment by Deepanjalitr** [comment]
> @Deepanjalitr, is the log validation utility report clear for all the flows?

@sandeepshahi , I have not verified all the flows using the validation utility

**Comment by sandeepshahi** [comment]
@Deepanjalitr, please perform a sanity using the [log validation utility](https://github.com/ONDC-Official/log-validation-utility) before resubmitting the logs.

**Comment by Deepanjalitr** [comment]
> @Deepanjalitr, please perform a sanity using the [log validation utility](https://github.com/ONDC-Official/log-validation-utility) before resubmitting the logs.

@sandeepshahi , sure

**Comment by Deepanjalitr** [comment]
Hi Sandeep,
  I was trying the validation APIs and a few errors seem invalid. For eg,
"schemaErr3": "/message/catalog/bpp~1providers/0/categories/3/id
categories.id should be alphanumeric and upto 12 characters" Can we ignore
these errors? Regards
Deepanjali T R

**Comment by sandeepshahi** [comment]
@Deepanjalitr, pls submit the utility output along with the logs. We'll check them.

**Comment by Deepanjalitr** [comment]
Hi @sandeepshahi 
I have resubmitted the logs after validating the flows using the APIs. Additionally, I have attached the validation API response, which includes a new key, "__comments__", for your reference.

**Comment by Deepanjalitr** [comment]
@sandeepshahi, Could you verify the logs submitted

**Review by sandeepshahi — APPROVED** [review]

**Pull request merged**
