### PR TITLE
UdyamWell seller tech logs

### PR DESCRIPTION
**Pull request by udyamwell1**
Please approve

### CODE REVIEW

**Review by bluecypher — CHANGES_REQUESTED** [review]
Flows are incomplete. Please submit logs for all the flows in Group B [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795) for verification

**Comment by udyamwell1** [comment]
> Flows are incomplete. Please submit logs for all the flows in Group B [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795) for verification

Will do that . Sir, we have confusion related to version. Can you please let us know If we are still in V 1.1 or V 1.2. It will be great help.

**Comment by bluecypher** [comment]
v1.2. Follow the contract [here](https://docs.google.com/document/d/1aRzox3_Dq0Q_SicIaKegdU7FpM5q8R1rjrA6vi8qF0E/edit)

**Comment by udyamwell1** [comment]
Okay. Thanks a lot

**Pull request closed without merging**
