### PR TITLE
Hubpe 1.2 logs

### PR DESCRIPTION
**Pull request by rajib-senrysa**

### CODE REVIEW

**Comment by rajib-senrysa** [comment]
@BLR-0118 @bluecypher

**Review by bluecypher — CHANGES_REQUESTED** [review]
Please submit flow 6 for RET 10 and for RET 11, test with a different seller app in preprod.

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
> Please submit flow 6 for RET 10 and for RET 11, test with a different seller app in preprod.

We have submitted flow #6 with one seller NP NDHGO @bluecypher

**Comment by bluecypher** [comment]
@rajib-senrysa, the flow 6 submitted is for RET 11. Pls submit logs for RET 10 as well. And test with a different seller NP in preprod (both buyer app and seller app should not be the same entity).

**Comment by bluecypher** [comment]
Please address the issues mentioned above and resubmit the PR

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
> @rajib-senrysa, the flow 6 submitted is for RET 11. Pls submit logs for RET 10 as well. And test with a different seller NP in preprod (both buyer app and seller app should not be the same entity).

@bluecypher, @BLR-0118  I need a few clarity

1. You mean to say that Hubpe & NDHGO as same entity so the logs can't be submitted for this? But it is not the same entity both are different product. I am little confused on this.
2. You want only step 6 to be submitted for both RET10 and RET11 or the entire flow as per the test case.

**Comment by bluecypher** [comment]
1. Ack, will merge the PR and review the logs
2. All the flows (1 to 6) must be submitted for both the domains RET10 and RET11
@rajib-senrysa

**Review by bluecypher — APPROVED** [review]

**Comment by rajib-senrysa** [comment]
> 1. Ack, will merge the PR and review the logs
> 2. All the flows (1 to 6) must be submitted for both the domains RET10 and RET11
>    @rajib-senrysa

Sure we will be submitting that Today

**Pull request merged**
