### PR TITLE
Retailware (SA: RET10) Order Flow logs

### PR DESCRIPTION
**Pull request by Retailware**
Hello,
We are a Retailware seller app, we have made changes as per the compliance checks. please check the logs for RET10 domain.

Note: 1. We are off-network for logistics
          2. We have uploaded logs validation utility reports.

### CODE REVIEW

**Review by sandeepshahi — CHANGES_REQUESTED** [review]
Can you submit flow 6 as part of a single order? No need to submit duplicate files as separate scenarios.

**Comment by Retailware** [comment]
We have submitted a single order for flow 6.

@sandeepshahi

**Comment by sandeepshahi** [comment]
@Retailware, There are duplicate files. You just need to submit flow 6 and not 6a 6b 6c separately just like other flows.

**Comment by Retailware** [comment]
ok, thanks

@sandeepshahi

**Review by sandeepshahi — APPROVED** [review]

**Pull request merged**
